cluster.name: "docker-cluster"
#network.bind_host: 0.0.0.0
network.host: 0.0.0.0
http.port: 9200
discovery.zen.minimum_master_nodes: 1
#discovery.type: single-node
#cluster.routing.allocation.disk.threshold_enabled: false
node.name: node1
node.master: false
node.data: true
http.cors.enabled: true
http.cors.allow-origin: "*"
discovery.zen.ping.unicast.hosts: ["elasticsearch","elasticsearch1","elasticsearch2"]
